
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */



/**
 *
 * @author USER
 */
public class choose_vehicles extends javax.swing.JFrame {

    /**
     * Creates new form choose_vehicles
     */
    public choose_vehicles() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton8 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        SHAPE = new javax.swing.JLabel();
        cz = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setLayout(null);

        jButton8.setBackground(new java.awt.Color(255, 255, 255));
        jButton8.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton8.setText("Medium Truck");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton8);
        jButton8.setBounds(590, 380, 150, 80);

        jButton7.setBackground(new java.awt.Color(255, 255, 255));
        jButton7.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton7.setText("Small Truck");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton7);
        jButton7.setBounds(440, 380, 130, 80);

        jButton6.setBackground(new java.awt.Color(255, 255, 255));
        jButton6.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton6.setText("Big Bus");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6);
        jButton6.setBounds(290, 380, 130, 80);

        jButton4.setBackground(new java.awt.Color(255, 255, 255));
        jButton4.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton4.setText("Microbus");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4);
        jButton4.setBounds(590, 230, 150, 80);

        jButton5.setBackground(new java.awt.Color(255, 255, 255));
        jButton5.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton5.setText("Medium Bus");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(140, 380, 130, 80);

        jButton3.setBackground(new java.awt.Color(255, 255, 255));
        jButton3.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton3.setText("Pickup van");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(440, 230, 130, 80);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton2.setText("Car/Jeep");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(290, 230, 130, 80);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        jButton1.setText("Motorcycle");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(140, 230, 130, 80);

        SHAPE.setBackground(new java.awt.Color(204, 0, 204));
        SHAPE.setForeground(new java.awt.Color(255, 0, 0));
        SHAPE.setIcon(new javax.swing.ImageIcon(getClass().getResource("/box.jpg"))); // NOI18N
        SHAPE.setText("jLabel1");
        jPanel1.add(SHAPE);
        SHAPE.setBounds(70, 120, 750, 480);

        cz.setBackground(new java.awt.Color(0, 0, 0));
        cz.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        cz.setForeground(new java.awt.Color(255, 255, 255));
        cz.setText("CHOOSE VEHICLE");
        jPanel1.add(cz);
        cz.setBounds(250, 30, 370, 110);

        jPanel2.setBackground(new java.awt.Color(105, 195, 192));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 870, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 750, Short.MAX_VALUE)
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 870, 750);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 871, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 751, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String v1="MOTORCYCLE";
        int ammount,ammount2,ammount3;
        String currency="cc",availabletk="tk";
         try {
        Connection connection =DriverManager.getConnection("jdbc:mysql://localhost:3306/bridgetolldb","root", "root");
        Statement stmnt=connection.createStatement();
           ResultSet rs=stmnt.executeQuery("SELECT * FROM bridgetolldb.padma where VEHICLES='"+v1+"'");
           if(rs.next())
           {
               String v2="tk";
              String s =rs.getString("TAKA");
              ammount=Integer.parseInt(s);
               Statement stmnt2=connection.createStatement();
               String query2="UPDATE bridgetolldb.totalcash SET cash = '"+ammount+"' WHERE currencyname='"+v2+"'";
               stmnt2.executeUpdate(query2);
               //String query="DELETE FROM clientinfodb.client WHERE ID='"+id+"'";
               
               
        Statement stmnt3=connection.createStatement();
           ResultSet rs2=stmnt3.executeQuery("SELECT * FROM bridgetolldb.totalcash where currencyname='"+currency+"'");
           if(rs2.next())
           {
               ammount2 =Integer.parseInt(rs2.getString("cash"));
               Statement stmnt4=connection.createStatement();
               ResultSet rs3=stmnt4.executeQuery("SELECT * FROM bridgetolldb.totalcash where currencyname='"+availabletk+"'");
               if(rs3.next()) {
               ammount3 =Integer.parseInt(rs3.getString("cash"));
               ammount2=ammount2+ammount3;
               
               Statement stmnt5=connection.createStatement();
               String query3="UPDATE bridgetolldb.totalcash SET cash = '"+ammount2+"' WHERE currencyname='"+currency+"'";
               stmnt5.executeUpdate(query3);
               }
           }
           }
           this.setVisible(false);
               new Emp_Checkout().setVisible(true);
    }
    catch (Exception e)
    {
    e.printStackTrace();
    }
        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        String v1="CAR/JEEP";
        int ammount,ammount2,ammount3;
        String currency="cc",availabletk="tk";
         try {
        Connection connection =DriverManager.getConnection("jdbc:mysql://localhost:3306/bridgetolldb","root", "root");
        Statement stmnt=connection.createStatement();
           ResultSet rs=stmnt.executeQuery("SELECT * FROM bridgetolldb.padma where VEHICLES='"+v1+"'");
           if(rs.next())
           {
               String v2="tk";
              String s =rs.getString("TAKA");
              ammount=Integer.parseInt(s);
               Statement stmnt2=connection.createStatement();
               String query2="UPDATE bridgetolldb.totalcash SET cash = '"+ammount+"' WHERE currencyname='"+v2+"'";
               stmnt2.executeUpdate(query2);
               //String query="DELETE FROM clientinfodb.client WHERE ID='"+id+"'";
               
               
        Statement stmnt3=connection.createStatement();
           ResultSet rs2=stmnt3.executeQuery("SELECT * FROM bridgetolldb.totalcash where currencyname='"+currency+"'");
           if(rs2.next())
           {
               ammount2 =Integer.parseInt(rs2.getString("cash"));
               Statement stmnt4=connection.createStatement();
               ResultSet rs3=stmnt4.executeQuery("SELECT * FROM bridgetolldb.totalcash where currencyname='"+availabletk+"'");
               if(rs3.next()) {
               ammount3 =Integer.parseInt(rs3.getString("cash"));
               ammount2=ammount2+ammount3;
               
               Statement stmnt5=connection.createStatement();
               String query3="UPDATE bridgetolldb.totalcash SET cash = '"+ammount2+"' WHERE currencyname='"+currency+"'";
               stmnt5.executeUpdate(query3);
               }
           }
           }
           this.setVisible(false);
               new Emp_Checkout().setVisible(true);
    }
    catch (Exception e)
    {
    e.printStackTrace();
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
String v1="PICKUP VAN";
        int ammount,ammount2,ammount3;
        String currency="cc",availabletk="tk";
         try {
        Connection connection =DriverManager.getConnection("jdbc:mysql://localhost:3306/bridgetolldb","root", "root");
        Statement stmnt=connection.createStatement();
           ResultSet rs=stmnt.executeQuery("SELECT * FROM bridgetolldb.padma where VEHICLES='"+v1+"'");
           if(rs.next())
           {
               String v2="tk";
              String s =rs.getString("TAKA");
              ammount=Integer.parseInt(s);
               Statement stmnt2=connection.createStatement();
               String query2="UPDATE bridgetolldb.totalcash SET cash = '"+ammount+"' WHERE currencyname='"+v2+"'";
               stmnt2.executeUpdate(query2);
               //String query="DELETE FROM clientinfodb.client WHERE ID='"+id+"'";
               
               
        Statement stmnt3=connection.createStatement();
           ResultSet rs2=stmnt3.executeQuery("SELECT * FROM bridgetolldb.totalcash where currencyname='"+currency+"'");
           if(rs2.next())
           {
               ammount2 =Integer.parseInt(rs2.getString("cash"));
               Statement stmnt4=connection.createStatement();
               ResultSet rs3=stmnt4.executeQuery("SELECT * FROM bridgetolldb.totalcash where currencyname='"+availabletk+"'");
               if(rs3.next()) {
               ammount3 =Integer.parseInt(rs3.getString("cash"));
               ammount2=ammount2+ammount3;
               
               Statement stmnt5=connection.createStatement();
               String query3="UPDATE bridgetolldb.totalcash SET cash = '"+ammount2+"' WHERE currencyname='"+currency+"'";
               stmnt5.executeUpdate(query3);
               }
           }
           
           }
           this.setVisible(false);
               new Emp_Checkout().setVisible(true);
    }
    catch (Exception e)
    {
    e.printStackTrace();
    }        
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        String v1="MICRO BUS";
        int ammount,ammount2,ammount3;
        String currency="cc",availabletk="tk";
         try {
        Connection connection =DriverManager.getConnection("jdbc:mysql://localhost:3306/bridgetolldb","root", "root");
        Statement stmnt=connection.createStatement();
           ResultSet rs=stmnt.executeQuery("SELECT * FROM bridgetolldb.padma where VEHICLES='"+v1+"'");
           if(rs.next())
           {
               String v2="tk";
              String s =rs.getString("TAKA");
              ammount=Integer.parseInt(s);
               Statement stmnt2=connection.createStatement();
               String query2="UPDATE bridgetolldb.totalcash SET cash = '"+ammount+"' WHERE currencyname='"+v2+"'";
               stmnt2.executeUpdate(query2);
               //String query="DELETE FROM clientinfodb.client WHERE ID='"+id+"'";
               
               
        Statement stmnt3=connection.createStatement();
           ResultSet rs2=stmnt3.executeQuery("SELECT * FROM bridgetolldb.totalcash where currencyname='"+currency+"'");
           if(rs2.next())
           {
               ammount2 =Integer.parseInt(rs2.getString("cash"));
               Statement stmnt4=connection.createStatement();
               ResultSet rs3=stmnt4.executeQuery("SELECT * FROM bridgetolldb.totalcash where currencyname='"+availabletk+"'");
               if(rs3.next()) {
               ammount3 =Integer.parseInt(rs3.getString("cash"));
               ammount2=ammount2+ammount3;
               
               Statement stmnt5=connection.createStatement();
               String query3="UPDATE bridgetolldb.totalcash SET cash = '"+ammount2+"' WHERE currencyname='"+currency+"'";
               stmnt5.executeUpdate(query3);
               }
           }
           }
           this.setVisible(false);
               new Emp_Checkout().setVisible(true);
    }
    catch (Exception e)
    {
    e.printStackTrace();
    } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        String v1="MEDIUM BUS";
        int ammount,ammount2,ammount3;
        String currency="cc",availabletk="tk";
         try {
        Connection connection =DriverManager.getConnection("jdbc:mysql://localhost:3306/bridgetolldb","root", "root");
        Statement stmnt=connection.createStatement();
           ResultSet rs=stmnt.executeQuery("SELECT * FROM bridgetolldb.padma where VEHICLES='"+v1+"'");
           if(rs.next())
           {
               String v2="tk";
              String s =rs.getString("TAKA");
              ammount=Integer.parseInt(s);
               Statement stmnt2=connection.createStatement();
               String query2="UPDATE bridgetolldb.totalcash SET cash = '"+ammount+"' WHERE currencyname='"+v2+"'";
               stmnt2.executeUpdate(query2);
               //String query="DELETE FROM clientinfodb.client WHERE ID='"+id+"'";
               
               
        Statement stmnt3=connection.createStatement();
           ResultSet rs2=stmnt3.executeQuery("SELECT * FROM bridgetolldb.totalcash where currencyname='"+currency+"'");
           if(rs2.next())
           {
               ammount2 =Integer.parseInt(rs2.getString("cash"));
               Statement stmnt4=connection.createStatement();
               ResultSet rs3=stmnt4.executeQuery("SELECT * FROM bridgetolldb.totalcash where currencyname='"+availabletk+"'");
               if(rs3.next()) {
               ammount3 =Integer.parseInt(rs3.getString("cash"));
               ammount2=ammount2+ammount3;
               
               Statement stmnt5=connection.createStatement();
               String query3="UPDATE bridgetolldb.totalcash SET cash = '"+ammount2+"' WHERE currencyname='"+currency+"'";
               stmnt5.executeUpdate(query3);
               }
           }
           }
           this.setVisible(false);
               new Emp_Checkout().setVisible(true);
    }
    catch (Exception e)
    {
    e.printStackTrace();
    } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String v1="BIG BUS";
        int ammount,ammount2,ammount3;
        String currency="cc",availabletk="tk";
         try {
        Connection connection =DriverManager.getConnection("jdbc:mysql://localhost:3306/bridgetolldb","root", "root");
        Statement stmnt=connection.createStatement();
           ResultSet rs=stmnt.executeQuery("SELECT * FROM bridgetolldb.padma where VEHICLES='"+v1+"'");
           if(rs.next())
           {
               String v2="tk";
              String s =rs.getString("TAKA");
              ammount=Integer.parseInt(s);
               Statement stmnt2=connection.createStatement();
               String query2="UPDATE bridgetolldb.totalcash SET cash = '"+ammount+"' WHERE currencyname='"+v2+"'";
               stmnt2.executeUpdate(query2);
               //String query="DELETE FROM clientinfodb.client WHERE ID='"+id+"'";
               
               
        Statement stmnt3=connection.createStatement();
           ResultSet rs2=stmnt3.executeQuery("SELECT * FROM bridgetolldb.totalcash where currencyname='"+currency+"'");
           if(rs2.next())
           {
               ammount2 =Integer.parseInt(rs2.getString("cash"));
               Statement stmnt4=connection.createStatement();
               ResultSet rs3=stmnt4.executeQuery("SELECT * FROM bridgetolldb.totalcash where currencyname='"+availabletk+"'");
               if(rs3.next()) {
               ammount3 =Integer.parseInt(rs3.getString("cash"));
               ammount2=ammount2+ammount3;
               
               Statement stmnt5=connection.createStatement();
               String query3="UPDATE bridgetolldb.totalcash SET cash = '"+ammount2+"' WHERE currencyname='"+currency+"'";
               stmnt5.executeUpdate(query3);
               }
           }
           }
           this.setVisible(false);
               new Emp_Checkout().setVisible(true);
    }
    catch (Exception e)
    {
    e.printStackTrace();
    } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        String v1="SMALL TRUCK";
       int ammount,ammount2,ammount3;
        String currency="cc",availabletk="tk";
         try {
        Connection connection =DriverManager.getConnection("jdbc:mysql://localhost:3306/bridgetolldb","root", "root");
        Statement stmnt=connection.createStatement();
           ResultSet rs=stmnt.executeQuery("SELECT * FROM bridgetolldb.padma where VEHICLES='"+v1+"'");
           if(rs.next())
           {
               String v2="tk";
              String s =rs.getString("TAKA");
              ammount=Integer.parseInt(s);
               Statement stmnt2=connection.createStatement();
               String query2="UPDATE bridgetolldb.totalcash SET cash = '"+ammount+"' WHERE currencyname='"+v2+"'";
               stmnt2.executeUpdate(query2);
               //String query="DELETE FROM clientinfodb.client WHERE ID='"+id+"'";
               
               
        Statement stmnt3=connection.createStatement();
           ResultSet rs2=stmnt3.executeQuery("SELECT * FROM bridgetolldb.totalcash where currencyname='"+currency+"'");
           if(rs2.next())
           {
               ammount2 =Integer.parseInt(rs2.getString("cash"));
               Statement stmnt4=connection.createStatement();
               ResultSet rs3=stmnt4.executeQuery("SELECT * FROM bridgetolldb.totalcash where currencyname='"+availabletk+"'");
               if(rs3.next()) {
               ammount3 =Integer.parseInt(rs3.getString("cash"));
               ammount2=ammount2+ammount3;
               
               Statement stmnt5=connection.createStatement();
               String query3="UPDATE bridgetolldb.totalcash SET cash = '"+ammount2+"' WHERE currencyname='"+currency+"'";
               stmnt5.executeUpdate(query3);
               }
           }
           }
           this.setVisible(false);
               new Emp_Checkout().setVisible(true);
    }
    catch (Exception e)
    {
    e.printStackTrace();
    } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        String v1="MEDIUM TRUCK";
        int ammount,ammount2,ammount3;
        String currency="cc",availabletk="tk";
         try {
        Connection connection =DriverManager.getConnection("jdbc:mysql://localhost:3306/bridgetolldb","root", "root");
        Statement stmnt=connection.createStatement();
           ResultSet rs=stmnt.executeQuery("SELECT * FROM bridgetolldb.padma where VEHICLES='"+v1+"'");
           if(rs.next())
           {
               String v2="tk";
              String s =rs.getString("TAKA");
              ammount=Integer.parseInt(s);
               Statement stmnt2=connection.createStatement();
               String query2="UPDATE bridgetolldb.totalcash SET cash = '"+ammount+"' WHERE currencyname='"+v2+"'";
               stmnt2.executeUpdate(query2);
               //String query="DELETE FROM clientinfodb.client WHERE ID='"+id+"'";
               
               
        Statement stmnt3=connection.createStatement();
           ResultSet rs2=stmnt3.executeQuery("SELECT * FROM bridgetolldb.totalcash where currencyname='"+currency+"'");
           if(rs2.next())
           {
               ammount2 =Integer.parseInt(rs2.getString("cash"));
               Statement stmnt4=connection.createStatement();
               ResultSet rs3=stmnt4.executeQuery("SELECT * FROM bridgetolldb.totalcash where currencyname='"+availabletk+"'");
               if(rs3.next()) {
               ammount3 =Integer.parseInt(rs3.getString("cash"));
               ammount2=ammount2+ammount3;
               
               Statement stmnt5=connection.createStatement();
               String query3="UPDATE bridgetolldb.totalcash SET cash = '"+ammount2+"' WHERE currencyname='"+currency+"'";
               stmnt5.executeUpdate(query3);
               }
           }
           }
           this.setVisible(false);
               new Emp_Checkout().setVisible(true);
    }
    catch (Exception e)
    {
    e.printStackTrace();
    } 
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(choose_vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(choose_vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(choose_vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(choose_vehicles.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new choose_vehicles().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel SHAPE;
    private javax.swing.JLabel cz;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
